export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const CREATE_QUESTION = 'CREATE_QUESTION';
export const GET_ALL_QUESTIONS = 'GET_RECENT_QUESTIONS';

export const CREATE_ANSWER = 'CREATE_ANSWER';
export const EDIT_ANSWER = 'EDIT_ANSWER';
export const DELETE_ANSWER = 'DELETE_ANSWER';
export const GET_MOST_ANSWERS_LIST  = 'MOST_ANSWERS_LIST';

export const GET_PROFILE_DETAILS = 'GET_PROFILE_DETAILS';
export const UPDATE_PROFILE_DETAILS = 'UPDATE_PROFILE_DETAILS';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD'

export const CREATE_RATING = 'CREATE_RATING';
export const DELETE_QUESTION_RATING = 'DELETE_QUESTION_RATING'
export const GET_QUESTION_RATINGS = 'GET_QUESTION_RATINGS';
